BulochkaWeb/Areas/Admin/Controllers/CompanyBranchController.cs
using Bulochka.DataAccess;
using Bulochka.DataAccess.Repository.IRepository;
using Bulochka.Models;
using Bulochka.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulochkaWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyBranchController : Controller
    {
        private string _tempDataMessage;

        private readonly IUnitOfWork _unitOfWork;

        public CompanyBranchController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _tempDataMessage = "";
        }

        public IActionResult Index()
        {
            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            CompanyBranch branch = new();

            if (id == null || id == 0)
            {
                //create
                return View(branch);
            }
            else
            {
                //update
                branch = _unitOfWork.CompanyBranch.GetFirstOrDefault(p => p.Id == id);
                return View(branch);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(CompanyBranch branch, IFormFile? file)
        {
            _tempDataMessage = "";
            if (ModelState.IsValid)
            {
                if (branch.Id == 0)
                {
                    _unitOfWork.CompanyBranch.Add(branch);
                    _tempDataMessage = "Филиал успешно добавлен";
                }
                else
                {
                    _unitOfWork.CompanyBranch.Update(branch);
                    _tempDataMessage = "Филиал успешно изменен";
                }

                _unitOfWork.Save();
                TempData["success"] = _tempDataMessage;
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var companyBranchList = _unitOfWork.CompanyBranch.GetAll();
            return Json(new { data = companyBranchList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var branch = _unitOfWork.CompanyBranch.GetFirstOrDefault(p => p.Id == id);
            if (branch == null)
            {
                return Json(new { success = false, message = "Ошибка во время удаления" });
            }

            _unitOfWork.CompanyBranch.Remove(branch);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Удалено успешно" });
        }

        #endregion

    }
}

BulochkaWeb/Areas/Admin/Controllers/ProductController.cs
using Bulochka.DataAccess;
using Bulochka.DataAccess.Repository.IRepository;
using Bulochka.Models;
using Bulochka.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulochkaWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private const string ImagesFolder = @"\images\products\";
        private string _tempDataMessage;

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _tempDataMessage = "";
        }

        public IActionResult Index()
        {
            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Product product = new();

            if (id == null || id == 0)
            {
                //create
                return View(product);
            }
            else
            {
                //update
                product = _unitOfWork.Product.GetFirstOrDefault(p => p.Id == id);
                return View(product);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Product product, IFormFile? file)
        {
            _tempDataMessage = "";
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    if (product.ImageUrl != null) DeleteOldImage(product);

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    product.ImageUrl = ImagesFolder + fileName + extension;
                }

                if (product.Id == 0)
                {
                    _unitOfWork.Product.Add(product);
                    _tempDataMessage = "Продукт успешно добавлен";
                }
                else
                {
                    _unitOfWork.Product.Update(product);
                    _tempDataMessage = "Продукт успешно изменен";
                }

                _unitOfWork.Save();
                TempData["success"] = _tempDataMessage;
                return RedirectToAction("Index");
            }

            return View(product);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll();
            return Json(new { data = productList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var product = _unitOfWork.Product.GetFirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return Json(new { success = false, message = "Ошибка во время удаления" });
            }

            DeleteOldImage(product);

            _unitOfWork.Product.Remove(product);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Удалено успешно" });
        }

        #endregion

        private void DeleteOldImage(Product product)
        {
            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, product.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
        }
    }
}

BulochkaWeb/Areas/Customer/Controllers/CartController.cs
using Bulochka.DataAccess.Repository.IRepository;
using Bulochka.Models;
using Bulochka.Models.ViewModels;
using Bulochka.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stripe.Checkout;
using System.Security.Claims;

namespace BulochkaWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private ShoppingCartVM ShoppingCartVM { get; set; }

        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
                    includeProperties: "Product"),
                OrderHeader = new()
            };
            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Product.Price * cart.Count);
            }

            return View(ShoppingCartVM);
        }

        public IActionResult SummaryDelivery()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
                    includeProperties: "Product"),
                OrderHeader = new(),
                PaymentOptionList = new SelectList(GetPaymentOptions(), "Value", "Text", 1),
            };
            ShoppingCartVM.OrderHeader.ApplicationUser =
                _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value);

            ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Product.Price * cart.Count);
            }

            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("SummaryDelivery")]
        [ValidateAntiForgeryToken]
        public IActionResult SummaryDeliveryPOST(ShoppingCartVM shoppingCartVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim == null) throw new ArgumentNullException(nameof(claim));
            
            SetListCart(shoppingCartVM, claim);
            SetUserInfo(shoppingCartVM, claim);
            SetOrderHeaderAddress(shoppingCartVM,
                shoppingCartVM.OrderHeader.ApplicationUser.City,
                shoppingCartVM.OrderHeader.ApplicationUser.StreetAddress,
                shoppingCartVM.OrderHeader.ApplicationUser.PostalCode);

            SetDefaultInformation(shoppingCartVM);
            CalculateTotal(shoppingCartVM);

            AddOrderHeaderInfoToDb(shoppingCartVM);
            AddOrderDetailInfoToDb(shoppingCartVM);

            if (shoppingCartVM.PaymentOption == SD.PaymentOptionOffline)
            {
                _unitOfWork.ShoppingCart.RemoveRange(shoppingCartVM.ListCart);
                _unitOfWork.Save();
                return RedirectToAction("Index", "Home");
            }
            else if (shoppingCartVM.PaymentOption == SD.PaymentOptionOnline)
            {
                var domain = "https://localhost:44324/";
                var options = new SessionCreateOptions
                {
                    PaymentMethodTypes = new List<string>
                    {
                        "card",
                    },
                    LineItems = new List<SessionLineItemOptions>(),
                    Mode = "payment",
                    SuccessUrl = domain + $"customer/cart/OrderConfirmation?id={shoppingCartVM.OrderHeader.Id}",
                    CancelUrl = domain + $"customer/cart/index",
                };

                foreach (var item in shoppingCartVM.ListCart)
                {
                    var sessionLineItem = new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long)(item.Product.Price * 100),
                            Currency = "rub",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = item.Product.Title,
                            },
                        },
                        Quantity = item.Count,
                    };
                    options.LineItems.Add(sessionLineItem);
                }

                var service = new SessionService();
                Session session = service.Create(options);

                _unitOfWork.OrderHeader.UpdateStripePaymentId(shoppingCartVM.OrderHeader.Id,
                    session.Id,
                    session.PaymentIntentId);
                _unitOfWork.Save();

                Response.Headers.Add("Location", session.Url);
                return new StatusCodeResult(303);
            }
            else
            {
                throw new InvalidDataException("invalid payment option");
            }
        }

        public IActionResult SummaryInCafe()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
                    includeProperties: "Product"),
                OrderHeader = new(),
                CompanyBranchList = _unitOfWork.CompanyBranch.GetAll().Select(
                    b => new SelectListItem
                    {
                        Text = b.City + ", " + b.StreetAddress,
                        Value = b.Id.ToString()
                    }),
                PaymentOptionList = new SelectList(GetPaymentOptions(), "Value", "Text", 1),
            };
            ShoppingCartVM.OrderHeader.ApplicationUser =
                _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value);

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Product.Price * cart.Count);
            }

            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("SummaryInCafe")]
        [ValidateAntiForgeryToken]
        public IActionResult SummaryPOSTInCafe(ShoppingCartVM shoppingCartVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim == null) throw new ArgumentNullException(nameof(claim));

            var companyBranch = _unitOfWork.CompanyBranch.GetFirstOrDefault(
                b => b.Id == shoppingCartVM.OrderHeader.PickUpPlaceId);

            SetListCart(shoppingCartVM, claim);
            SetUserInfo(shoppingCartVM, claim);
            SetOrderHeaderAddress(shoppingCartVM,
                companyBranch.City,
                companyBranch.StreetAddress,
                companyBranch.PostalCode);

            SetDefaultInformation(shoppingCartVM);
            CalculateTotal(shoppingCartVM);

            AddOrderHeaderInfoToDb(shoppingCartVM);
            AddOrderDetailInfoToDb(shoppingCartVM);

            if (shoppingCartVM.PaymentOption == SD.PaymentOptionOffline)
            {
                _unitOfWork.ShoppingCart.RemoveRange(shoppingCartVM.ListCart);
                _unitOfWork.Save();
                return RedirectToAction("Index", "Home");
            }
            else if (shoppingCartVM.PaymentOption == SD.PaymentOptionOnline)
            {
                var domain = "https://localhost:44324/";
                var options = new SessionCreateOptions
                {
                    PaymentMethodTypes = new List<string> { "card" },
                    LineItems = new List<SessionLineItemOptions>(),
                    Mode = "payment",
                    SuccessUrl = domain + $"customer/cart/OrderConfirmation?id={shoppingCartVM.OrderHeader.Id}",
                    CancelUrl = domain + $"customer/cart/index",
                };

                foreach (var item in shoppingCartVM.ListCart)
                {
                    var sessionLineItem = new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long)(item.Product.Price * 100),
                            Currency = "rub",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = item.Product.Title,
                            },
                        },
                        Quantity = item.Count,
                    };
                    options.LineItems.Add(sessionLineItem);
                }

                var service = new SessionService();
                Session session = service.Create(options);

                _unitOfWork.OrderHeader.UpdateStripePaymentId(shoppingCartVM.OrderHeader.Id,
                    session.Id,

BulochkaWeb/Views/Shared/_Layout.cshtml
@using Bulochka.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulochka</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Bulochka</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Управление Контентом</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Каталог Товаров</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CompanyBranch" asp-action="Index">Список Филиалов</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Создать пользователя</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Employee" asp-controller="CompanyBranchOrders" asp-action="Index">Заказы</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-basket"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="OrderHistory" asp-action="Index">
                                <i class="bi bi-clock-history"></i>
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Поиск</button>
                        </form>*@
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - Bulochka
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/nbc5hb0k6mhffbdgzncht25iyogindewkh8nld59wrznstnb/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulochkaWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}